language: node_js

node_js: 
  - "14"
caches:
  directories:
    - node_modules
script: 
 - npm run-script build

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: www.appeal.icu
    region: ap-northeast-2
    skip_cleanup: true
    local_dir: build
    on:
      branch: master

notifications:
  email:
    recipients:
      - ma8511@naver.com